server {
    listen       80;
    listen  [::]:80;
    server_name  localhost;
    root /usr/share/nginx/html;  # Make sure this is the correct path
    index index.html index.htm;

    location / {
        try_files $uri $uri/ /index.html;
    }
}